// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'7bde3b7a67b9be3bc2c64508a7798bad050fc658b6e8328bf71f88a28834c16f'>;
export type ExecutionHash =
  ExecutionHashBase<'ee9f0968535416d94352c96a1dfb0d9fa11aa963c78654cbaf5bc05203e1ba81'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Cv: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly file: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Profile: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly photo: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly bio: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly role: 'TALENT' | 'RECRUITER' | 'ADMIN';
      readonly signUpMethod: 'EMAIL' | 'GOOGLE' | 'LinkedIn';
      readonly resetPasswordToken: CodecTypes['pg/text@1']['output'] | null;
      readonly resetPasswordTokenExpiry:
        CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly verificationToken: CodecTypes['pg/text@1']['output'] | null;
      readonly verifiedAt:
        CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Cv: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly file: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Profile: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly photo: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly bio: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly role: 'TALENT' | 'RECRUITER' | 'ADMIN';
      readonly signUpMethod: 'EMAIL' | 'GOOGLE' | 'LinkedIn';
      readonly resetPasswordToken: CodecTypes['pg/text@1']['input'] | null;
      readonly resetPasswordTokenExpiry:
        CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly verificationToken: CodecTypes['pg/text@1']['input'] | null;
      readonly verifiedAt:
        CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly cv: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly file: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly profile: {
      readonly bio: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly photo: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly password: CodecTypes['pg/text@1']['output'] | null;
      readonly resetPasswordToken: CodecTypes['pg/text@1']['output'] | null;
      readonly resetPasswordTokenExpiry:
        CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly role: 'TALENT' | 'RECRUITER' | 'ADMIN';
      readonly signUpMethod: 'EMAIL' | 'GOOGLE' | 'LinkedIn';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly verificationToken: CodecTypes['pg/text@1']['output'] | null;
      readonly verifiedAt:
        CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly cv: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly file: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly profile: {
      readonly bio: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly photo: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly password: CodecTypes['pg/text@1']['input'] | null;
      readonly resetPasswordToken: CodecTypes['pg/text@1']['input'] | null;
      readonly resetPasswordTokenExpiry:
        CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly role: 'TALENT' | 'RECRUITER' | 'ADMIN';
      readonly signUpMethod: 'EMAIL' | 'GOOGLE' | 'LinkedIn';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly verificationToken: CodecTypes['pg/text@1']['input'] | null;
      readonly verifiedAt:
        CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes['pg/uuid@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    password: CodecTypes['pg/text@1']['output'] | null;
    name: CodecTypes['pg/text@1']['output'] | null;
    role: 'TALENT' | 'RECRUITER' | 'ADMIN';
    signUpMethod: 'EMAIL' | 'GOOGLE' | 'LinkedIn';
    resetPasswordToken: CodecTypes['pg/text@1']['output'] | null;
    resetPasswordTokenExpiry:
      CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    verificationToken: CodecTypes['pg/text@1']['output'] | null;
    verifiedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    profile: public_Profile | null;
    readonly [RelationKeys]?: 'profile';
  };
  export type public_Profile = {
    id: CodecTypes['pg/uuid@1']['output'];
    photo: CodecTypes['pg/text@1']['output'] | null;
    phone: CodecTypes['pg/text@1']['output'] | null;
    bio: CodecTypes['pg/text@1']['output'] | null;
    userId: CodecTypes['pg/uuid@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
  export type public_Cv = {
    id: CodecTypes['pg/uuid@1']['output'];
    file: CodecTypes['pg/text@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Profile: Models.public_Profile;
    Cv: Models.public_Cv;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly cv: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly file: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'cv_userId_idx_a489d58a';
                  readonly prefix: 'cv_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'cv';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'cv_user_id_fkey';
                },
              ];
            };
            readonly profile: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly photo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly bio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly userId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'profile';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'profile_user_id_fkey';
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'TALENT'>;
                  };
                };
                readonly signUpMethod: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'EMAIL'>;
                  };
                };
                readonly resetPasswordToken: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly resetPasswordTokenExpiry: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly verificationToken: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly verifiedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['TALENT', 'RECRUITER', 'ADMIN'];
            };
            readonly SignUpMethod: {
              readonly kind: 'valueSet';
              readonly values: readonly ['EMAIL', 'GOOGLE', 'LinkedIn'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'User';
    };
    readonly profile: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Profile';
    };
    readonly cv: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Cv';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Cv: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/uuid@1';
                };
              };
              readonly file: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/uuid@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'cv';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly file: { readonly column: 'file' };
                readonly userId: { readonly column: 'userId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Profile: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/uuid@1';
                };
              };
              readonly photo: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly bio: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/uuid@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'profile';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly photo: { readonly column: 'photo' };
                readonly phone: { readonly column: 'phone' };
                readonly bio: { readonly column: 'bio' };
                readonly userId: { readonly column: 'userId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/uuid@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly password: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly signUpMethod: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly resetPasswordToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly resetPasswordTokenExpiry: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly verificationToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly verifiedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly profile: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Profile';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly password: { readonly column: 'password' };
                readonly name: { readonly column: 'name' };
                readonly role: { readonly column: 'role' };
                readonly signUpMethod: { readonly column: 'signUpMethod' };
                readonly resetPasswordToken: {
                  readonly column: 'resetPasswordToken';
                };
                readonly resetPasswordTokenExpiry: {
                  readonly column: 'resetPasswordTokenExpiry';
                };
                readonly verificationToken: {
                  readonly column: 'verificationToken';
                };
                readonly verifiedAt: { readonly column: 'verifiedAt' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'TALENT'; readonly value: 'TALENT' },
              { readonly name: 'RECRUITER'; readonly value: 'RECRUITER' },
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
            ];
          };
          readonly SignUpMethod: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'EMAIL'; readonly value: 'EMAIL' },
              { readonly name: 'GOOGLE'; readonly value: 'GOOGLE' },
              { readonly name: 'LinkedIn'; readonly value: 'LinkedIn' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'cv';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'cv';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'profile';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'profile';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
